trigger:
  - feature*
  - develop
  - stage
  - integration
  - qa
  - main
  - hotfix*
  - drop*

pool: Windows Agent

steps:
  - task: FuncToolsInstaller@0
    inputs:
      version: 'latest'

  - task: DownloadSecureFile@1
    displayName: 01 | download maven settings file
    name: settingsxml
    inputs:
      secureFile: 'settings.xml'

  - task: PowerShell@2
    displayName: 02 | configure maven settings
    inputs:
      targetType: 'inline'
      script: |
        New-Item -Type Directory -Force "${HOME}/.m2"
        Copy-Item -Force "$(settingsxml.secureFilePath)" "${HOME}/.m2/settings.xml"

  - task: PowerShell@2
    displayName: 1 || check for infra chage
    inputs:
      targetType: 'inline'
      script: |
        $files=$(git diff HEAD HEAD~ --name-only)
        $temp=$files -split ' '
        $count=$temp.Length
        echo "Total changed $count files"
        For ($i=0; $i -lt $temp.Length; $i++)
        {
          $name=$temp[$i]
          echo "this is $name file"
          if ($name -like "artifacts/templates/*" -OR $name -contains "pom.xml")
            {
              Write-Host "##vso[task.setvariable variable=infrastructure_changed]True"
              New-Item -Path 'infrastructure_changed.txt' -ItemType File -Force
              Get-ChildItem -Recurse infrastructure_changed.txt | Format-Table FullName 
             }
        }

  - task: Maven@3
    displayName: 2 || build code
    inputs:
      mavenPomFile: pom.xml
      mavenOptions: -Xmx3072m
      javaHomeOption: JDKVersion
      jdkVersionOption: '1.17'
      jdkArchitectureOption: x64
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      codeCoverageToolOption: jaCoCo
      checkStyleRunAnalysis: true
      pmdRunAnalysis: true
      findBugsRunAnalysis: false
      goals: clean package

  - task: CopyFiles@2
    displayName: 5 || copy all artifacts
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: |
        **/artifacts/**
        **/azure-functions/**
        infrastructure_changed.txt
        pom.xml
      TargetFolder: $(Build.ArtifactStagingDirectory)
      OverWrite: true


  - task: PublishBuildArtifacts@1
    displayName: 6 || publish artifacts
    condition: ne(variables['Build.SourceBranchName'], 'feature/*')
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)